// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Printf = require("bs-platform/lib/js/printf.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component1$ReactHooksTemplate = require("./Component1.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component1$ReactHooksTemplate.make, {
          message: "Hello! Click this text."
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "index2");

Printf.printf(/* Format */[
      /* String_literal */Block.__(11, [
          "foo",
          /* End_of_format */0
        ]),
      "foo"
    ]);

/*  Not a pure module */
